---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# vov

<!-- badges: start -->
<!-- badges: end -->

The goal of vov is to wrap [vov.css](https://github.com/vaibhav111tandon/vov.css) in R for easier usage in shiny applications.

## Usage

You can use `vov` in a shiny app like so:

```{r, eval=FALSE}
library(shiny)
library(vov)

ui <- fluidPage(
  use_vov(),
  swivel_vertical(h1("fade_in_bottom_left"))
)

server <- function(input, output, session) {

}

shinyApp(ui, server)
```

Where `swivel_vertical(h1("fade_in_bottom_left"))` returns:

```{r, echo=FALSE}
library(shiny)
library(vov)
```


```{r}
x <- swivel_vertical(h1("hello world!"))
print(x)
```

If you don't want to load this package, you can just do something like:

```{r}
x <- tags$div(h1("hello world"), class = "vov swivel-vertical")
print(x)
```

